#!/bin/sh
module="scull"
device="scull"
mode="664"

case "$1" in
    start)
        echo "Starting $module"
        modprobe $module || exit 1
        # Retrieve major number
        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
        
        # Create device nodes
        rm -f /dev/${device}[0-3]
        mknod /dev/${device}0 c $major 0
        mknod /dev/${device}1 c $major 1
        mknod /dev/${device}2 c $major 2
        mknod /dev/${device}3 c $major 3
        
        # Set permissions
        group="staff"
        grep -q '^staff:' /etc/group || group="wheel"
        chgrp $group /dev/${device}[0-3]
        chmod $mode  /dev/${device}[0-3]
        ;;
    stop)
        echo "Stopping $module"
        # unload module
        rmmod $module || exit 1
        # remove device nodes
        rm -f /dev/${device}[0-3]
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
